name: ReviewGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run ReviewGPT
        uses: DanielGross/ReviewGPT@main
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
